image: docker

stages:
    - build
    - tests
    
build_dissertation:
  image: blang/latex
  stage: build
  script:
    - latexmk -pdf -cd docs/dissertation/dissertation.tex
  artifacts:
    paths:
      - "*.pdf"

build_builder:
  image: docker
  stage: build
  script:
    - docker build -t nutriplotterapp/builder:latest ./nutriplotterapp
    - docker login -u ${dockerLogin} -p ${dockerPassword}
    - docker push ${dockerLogin}/builder:latest

build_android:
  image: ${dockerLogin}/builder:latest
  stage: build
  
  script:
    - cd ./nutriplotterapp
    - npm install
    - npm install expo-cli turtle-cli gulp-cli
    - EXPO_USERNAME=${CIuser}
    - EXPO_PASSWORD=${CIpass}
    - npm expo login -u "${CIuser}" -p "${CIpass}"
    - npm expo fetch:android:keystore
    - npm expo build:android
